app = "fly-icecast"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8888
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 225
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "4s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
